In [ ]:
import pandas as pd
import numpy as np
import networkx as nx
import operator as op
import matplotlib.pyplot as plt
import numpy.linalg
import cmath
import scipy.optimize as optimize
import scipy as sp

In [ ]:
dataset=pd.read_csv("filename.csv", sep=" ", header=None)
#data.columns= [("slayer_id","source_id"), ("target_id", "tlayer_id")]

In [ ]:
temp_Graph = nx.from_numpy_matrix(temp)
step_mat = np.zeros((mat_size,mat_size))
step_mat
A = nx.adjacency_matrix(data)
def graph_creator(dataset, n, N):
    nrows = len(dataset)
    end = round(data_rows/n)
    start=0
    stop=end
    for pointer in range(0,nrows,end):
        vertices_graph(dataset.iloc[start:stop],N)
        edges_graph(dataset.iloc[start:stop],N)    
        start = start + end
        stop = start + step
        #print if need to show
#print(nx.info(a))
mat_size = len(dataset)
#print(dataset)
def volume_of_grapsh_vertices(dataset,N):
    l = layer_create(dataset,N)
    nodes_list=[]
    for t in l:
        G=graph(dataset, l[0], [1])
        nodes_list.append(len(G.graph.nodes()))
    return(nodes_list)
    def vertices_graph(dataset,N):
    #T=[]
    mat_size = len(A)
    print("Graph of Size", mat_size,":")
    print(A)
    
    time_intervals = create_intervals(dataset,N)
    for time_interval in time_intervals:
        T.append(time_interval[0])
    k = T  
    y = volume_of_grapsh_vertices(dataset,N)
    N = len(y)
    k = range(N)

Graph of Size 18 :
[[0 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [1 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 0 1 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 1 1 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0]
 [0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 1 0]
 [0 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 1 1]
 [0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0]]


In [ ]:
#slice the dataset or #reshaping 
#dataset=data.iloc[0:500]

In [ ]:
 for i in range(nodes_list):
      xl = x
      #starts with last node
      x = xl.copy() 
      for n in x:
          for nbr in G_symmetric[n]:
            w = G_symmetric[n][nbr].get('matsize', 1) 
            largest = eigenvector.flatten().real
            x[nbr] += xlast[n] * w

      norm = sp.sign(largest.sum()) * sp.linalg.norm(largest) or 1
      x = {k: v / norm for k, v in x.items()}
      pr=largest/norm
      #print(dict(zip(G, largest / norm)))
      # converging 
      if sum(abs(x[n] - xlast[n]) for n in x) < nnodes * tol:
        print(x) 
# direct function nx.pagerank()
def m_pagerank_centrality(n, ia, ja, max_p, l_i, l_j):
    mpr = np.zeros(k, dtype=np.float64)
    for i in range(k): 
        i = np.empty(k)
        iptr=0  
        lptr=1 
        j = np.empty((k,max_p))
        jptr= np.zeros(k)  
       for k in x: 
        d = -np.ones(k,dtype=np.int32); d[s] = 0
        m_i= sp.sign(dataset,iptr,jptr)(lptr,l_max)edges_graph(dataset.iloc[start:stop],N)  
        Q = np.empty(n,dtype=np.uint32)         
            for w in ja[ia[v]:ia[v + 1]]: # loop on neighbour of v  
        for w in S[S_ptr::-1]:
            for v in P[w,0:P_ptr[w]]:
                delta[v] += (sigma[v]/sigma[w]) * (1 + delta[w])
            mpr=x+m_i+delta[v]
    return mpr
    # Calculate for all Nodes
degreeCentralityValues = [m_pagerank_centrality(a) for a in range(mat_size)]
print("Centrality Values: \n", mpr)
       # Check for convergence 


Graph of Size 18 :
[[0 1 1 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0
  0 0 0 0]
 [1 0 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0
  0 0 0 0]
 [1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 0 0 1 1
  1 0 1 1]
 [1 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 1]
 [1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 0 0 1 1 1
  1 0 0 1]
 [0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1
  1 1 1 0]
 [0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 0
  1 1 1 0]
 [1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 0 0 1 1
  1 0 1 1]
 [0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 0 1 0 0 1 1 0 0 1
  1 1 0 0]
 [0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 0
  1 1 1 0]
 [1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 0 0 1 1
  1 0 1 1]
 [1 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 0 0 